# POSTGRES_HOST_AUTH_METHOD=trust
services:
  app:
    build: .
    volumes:
      - .:/usr/src/01_vezbe_uvod/
    ports:
      - 5000:5000
    env_file:
      - ./.env
    entrypoint: /bin/bash
    tty: true
    user: root
    depends_on:
      - db
    network_mode: host

  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    expose:
      - 5432
    ports:
      - 5432:5432
    network_mode: host
    environment:
      - POSTGRES_PASSWORD=pas0123

volumes:
  postgres_data: